### ISSUE TITLE
Certificate rotation

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#234]
We need to ensure we rotate all certificates to avoid expiration.
This is tracked in https://github.com/SovereignCloudStack/issues/issues/155

**Comment by garloff** [comment]
Tracked here now.
I see three places where to enable kubelet *client* certificate rotation:
configmap kube-system/kubelet-config-1.xx:
```
data:
  kubelet: |
    rotateCertificates: true
```
and in KubeadmControlPlane in cluster-template.yaml
```
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
          rotateCertificates: true
    joinConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
          rotateCertificates: true
```
which I believe will be propagated to `/var/lib/kubelet/kubeadm-flags.env` on the deployed nodes.
Do we need to tweak both places?
The setting in the configmap already seems to be there in newer versions, will need to research where it was added.
