### ISSUE TITLE
etcd maintenance

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#258]
As cluster operator, I want to avoid that etcd causes trouble.

etcd could become big and slow and ultimately so large, that it refuses writes.
We have observed this debugging the GXFS staging cluster.
https://input.osb-alliance.de/p/2022-scs-gxfs-cluster-debugging

To learn from this, we may want to tweak the etcd setup on the control nodes.
- [x] etcd parameters that limit the history and cause compaction and/or defragmentation
- [x] regular maintenance jobs on the node to maintain etcd's health
- [ ] detecting trouble on the node and raising alarms
- [ ] create documentation how to address potential (remaining) challenges

**Comment by garloff** [comment]
k8s should have limited to 110 pods per node to prevent this. Has this limit been lifted in our cluster?

**Comment by garloff** [comment]
rate limit needed for k8s API needed to protect cluster

**Comment by garloff** [comment]
@janiskemper to document recommended default rate limits

**Comment by garloff** [comment]
Discussion:
- We could add --auto-compaction-retention=10 parameter to etcd (to keep 10hrs of key history, removing anything older than 10hrs every hour), BUT it seems that kubernetes controller already does compaction for us, so this would only be a second line of defense in case this somehow got broken. Is this really advisable?
- Have a nightly systemd.timer job (or cron job) that calls etcdctl defrag on the control plane nodes; put some random delay to avoid all nodes doing defrag at the same time. (Ideally, defrag runs much shorter than a reelection timeout, but you never know)
- For kubeapi rate limit, I found some rancher docs ... adding a rate-limiting admission controller. https://rancher.com/docs/rke/latest/en/config-options/rate-limiting/ Is this rancher specific?
  Apart from this, we could add a qos policy (limit the *bandwidth*) to the loadbalancer address (in front of kubeapi) at openstack level, which seems somewhat suboptimal.

**Comment by batistein** [comment]
I would also recommend to use auto-compaction-retention. But I would suggest something like:
```
auto-compaction-mode: revision
auto-compaction-retention: 10000
```

I really like the idea of having a systemd service (more than cron) that calls etcdctl. 
I would also recommend to add a target on the node problem detector.

EventRateLimit is one of the really important configuration we need to do for beeing production-ready. And no it's not rancher specific. 
We should also set: `max-requests-inflight and max-mutating-requests-inflight` on the kube-apiserver
We could also think about using [FlowControl](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/flow-schema-v1beta2/).
Limiting anything on the openstack level is a bad idea, because this isn't portable to any other provider.

**Comment by batistein** [comment]
Our flags for etcd to be set in KubeadmControlPlane:
```
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
          extraArgs:
            cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
            cert-file: /etc/kubernetes/pki/etcd/server.crt
            key-file: /etc/kubernetes/pki/etcd/server.key
            client-cert-auth: "true"
            auto-tls: "false"
            peer-client-cert-auth: "true"
            peer-auto-tls: "false"
            trusted-ca-file: /etc/kubernetes/pki/etcd/ca.crt
            heartbeat-interval: "300"
            election-timeout: "3000"
            snapshot-count: "5000"
            quota-backend-bytes: "2147483648" # 2×1024×1024×1024 - 2GB
            auto-compaction-mode: periodic
            auto-compaction-retention: 6h
```
postKubeadmCommand:
```
  - ionice -c2 -n0 -p `pgrep etcd`
```

In the node image for the control-planes:

```
ETCD_VER=v3.4.20 #https://github.com/etcd-io/etcd/releases
mkdir -p /tmp/etcd-download-test
curl -L https://github.com/etcd-io/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1
mv /tmp/etcd-download-test/etcdctl /usr/local/sbin/etcdctl && chmod +x /usr/local/sbin/etcdctl
rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
rm -rf /tmp/etcd-download-test

mkdir -p /var/lib/etcd
chmod 700 /var/lib/etcd

cat > /etc/systemd/system/etcd-defrag.service <<'EOF'
[Unit]
Description=Run etcdctl defrag
Documentation=https://etcd.io/docs/v3.3.12/op-guide/maintenance/#defragmentation
After=network.target
[Service]
Type=oneshot
Environment="LOG_DIR=/var/log"
Environment="ETCDCTL_API=3"
ExecStart=/usr/local/sbin/etcdctl --cert /etc/kubernetes/pki/etcd/peer.crt --key /etc/kubernetes/pki/etcd/peer.key --cacert /etc/kubernetes/pki/etcd/ca.crt defrag
[Install]
WantedBy=multi-user.target
EOF


cat > /etc/systemd/system/etcd-defrag.timer <<'EOF'
[Unit]
Description=Run etcd-defrag.service every day
After=network.target
[Timer]
OnCalendar=*-*-* 02:00:0
RandomizedDelaySec=10m
[Install]
WantedBy=multi-user.target
EOF

systemctl enable etcd-defrag.service
systemctl enable etcd-defrag.timer
```
