### ISSUE TITLE
Feature: Support second nginx-ingress-controller for internal services

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#567]
I think supporting a second ingress-controller for internal services like kubernetes-dashboard etc. that shouldn‘t be publicly accessible could be useful.

Access to the LoadBalancer service could be restricted via spec.loadBalancerSourceRanges at least if octavia load balancers are used.

IngressClass e.g. "nginx-internal":
https://github.com/kubernetes/ingress-nginx/blob/8f54b538d9b32649411d9e507ca38fbee55ce51c/docs/user-guide/multiple-ingress.md?plain=1

It also needs to be considered which ingress controller should be the default one if no IngressClass is provided in an ingress resource.

**Comment by Nils98Ar** [comment]
Supporting multiple ingresses and ingress classes could be easier via helm: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx

Maybe we could install the "default" nginx-ingress with these values and releaseName `ingress-nginx`:
```
controller:
  allowSnippetAnnotations: true
  config:
    proxy-real-ip-cidr: 0.0.0.0/0
    use-proxy-protocol: "true"
  image:
    tag: v1.9.3
  ingressClass: nginx
  ingressClassResource:
    default: true
    name: nginx
  networkPolicy:
    enabled: true
  service:
    annotations:
      loadbalancer.openstack.org/enable-health-monitor: "true"
      loadbalancer.openstack.org/proxy-protocol: "true"
```

And anyone can deploy additional nginx-ingress controllers under another releaseName even in the same namespace, e.g. an `ingress-nginx-internal` by changing/adding the following values:
```
controller:
  ingressClassResource:
    name: nginx-internal
    default: false
  ingressClass: nginx-internal
  service:
    loadBalancerSourceRanges: ["X.X.X.X/XX","X.X.X.X/XX"]
```
