### ISSUE TITLE
Etcd metrics not reachable for prometheus

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#650]
Unauthenticated http access to port `2381` (default of kube-prometheus-stack with prometheus-operator) not working.

**Comment by Nils98Ar** [comment]
Https endpoint (port+scheme) and client certificate authentication need to be configured in kube-prometheus-stack values.
```
    kubeEtcd:
      service:
        port: 2379
        targetPort: 2379
      serviceMonitor:
        scheme: https
        caFile: /etc/prometheus/secrets/etcd-certs/ca.crt
        certFile: /etc/prometheus/secrets/etcd-certs/client.crt
        keyFile: /etc/prometheus/secrets/etcd-certs/client.key
    prometheus:
      prometheusSpec:
        secrets:
          - etcd-certs
```

The ca (crt) and client certificate (crt+key) must be provided in the secret etcd-certs with keys `ca.crt`, `client.crt` and `client.key`.
The ca cert can be found in the management cluster (`kind-kind`) in the workload cluster namespace in the secret `<cluster name>-ca`. Propably the certificate in the secret `<cluster name>-etcd` could also be re-used as client certificate...
